# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uconsignee_address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='udetail_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upostcode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
