# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-13 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0002_auto_20190430_1527'),
        ('df_goods', '0002_auto_20190510_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='购买价格')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单id')),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('o_is_pay', models.BooleanField(default=False, verbose_name='支付状态')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='总金额')),
                ('oaddress', models.CharField(max_length=100, verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.OrderInfo', verbose_name='所属订单'),
        ),
    ]
